<a href="https://colab.research.google.com/github/GracenAll/Final-Project/blob/main/Gracen_Project1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas 
import time 
import random
#pytz

In [2]:
data = pandas.read_csv("https://weather.visualcrossing.com/VisualCrossingWebServices/rest/services/timeline/Swannanoa%20NC%2028778/today?unitGroup=metric&elements=datetime%2CdatetimeEpoch%2Cname%2Caddress%2CresolvedAddress%2Clatitude%2Clongitude%2Ctempmax%2Ctempmin%2Ctemp%2Cfeelslikemax%2Cfeelslikemin%2Cfeelslike%2Cdew%2Chumidity%2Cprecip%2Cprecipprob%2Cprecipcover%2Cpreciptype%2Csnow%2Csnowdepth%2Cwindgust%2Cwindspeed%2Cwinddir%2Cpressure%2Ccloudcover%2Cvisibility%2Csolarradiation%2Csolarenergy%2Cuvindex%2Csevererisk%2Csunrise%2Csunset%2Cconditions%2Cdescription%2Cicon&include=hours&key=RC2PTRJ6EXHUFGFNUJJDTPTAH&contentType=csv")
data

,name,address,resolvedAddress,latitude,longitude,datetime,temp,feelslike,dew,humidity,...,winddir,sealevelpressure,cloudcover,visibility,solarradiation,solarenergy,uvindex,severerisk,conditions,icon
0,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T00:00:00,8.0,6.2,4.9,80.79,...,143,1021.9,100,16.0,0,NaN,0,10,Overcast,cloudy
1,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T01:00:00,7.4,5.4,3.3,75.61,...,52,1021.7,100,16.0,0,NaN,0,10,Overcast,cloudy
2,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T02:00:00,7.3,6.5,2.3,70.83,...,126,1021.7,100,16.0,0,NaN,0,10,Overcast,cloudy
3,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T03:00:00,6.8,5.5,2.3,73.38,...,124,1022.2,100,16.0,0,NaN,0,10,Overcast,cloudy
4,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T04:00:00,6.1,4.6,2.2,76.21,...,140,1022.9,100,16.0,0,NaN,0,10,Overcast,cloudy
5,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T05:00:00,5.6,3.6,2.7,81.78,...,146,1022.9,100,16.0,0,NaN,0,10,Overcast,cloudy
6,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T06:00:00,5.0,3.0,2.1,81.66,...,125,1023.0,100,16.0,0,NaN,0,10,Overcast,cloudy
7,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T07:00:00,4.4,1.6,2.1,84.75,...,143,1024.0,100,16.0,0,NaN,0,10,Overcast,cloudy
8,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T08:00:00,3.9,1.0,1.6,84.49,...,109,1024.3,100,16.0,2,0.0,0,10,Overcast,cloudy
9,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T09:00:00,3.9,1.0,1.0,81.12,...,142,1024.8,100,16.0,11,0.0,0,10,Overcast,cloudy
10,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T10:00:00,2.3,0.1,1.2,92.43,...,140,1022.0,76,16.4,136,0.5,1,10,Partially cloudy,partly-cloudy-day
11,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T11:00:00,3.4,2.1,1.7,88.62,...,140,1022.0,73,15.9,280,1.0,3,10,Partially cloudy,partly-cloudy-day
12,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T12:00:00,3.9,1.9,1.7,85.56,...,150,1021.0,70,15.6,353,1.3,4,10,Partially cloudy,partly-cloudy-day
13,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T13:00:00,4.5,3.3,1.7,82.03,...,150,1021.0,63,16.4,151,0.5,2,10,Partially cloudy,partly-cloudy-day
14,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T14:00:00,5.0,3.9,1.7,79.22,...,150,1020.0,54,16.3,283,1.0,3,10,Partially cloudy,partly-cloudy-day
15,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T15:00:00,5.0,3.9,1.7,79.22,...,140,1021.0,42,16.8,217,0.8,2,10,Partially cloudy,partly-cloudy-day
16,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T16:00:00,5.0,3.9,1.7,79.22,...,130,1020.0,38,15.8,107,0.4,1,10,Partially cloudy,partly-cloudy-day
17,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T17:00:00,3.9,2.6,1.2,82.54,...,130,1020.0,44,15.5,17,0.1,0,10,Partially cloudy,partly-cloudy-day
18,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T18:00:00,3.4,2.1,0.6,81.89,...,120,1020.0,45,13.8,0,0.0,0,10,Partially cloudy,partly-cloudy-night
19,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T19:00:00,2.3,0.8,0.0,84.76,...,120,1021.0,46,14.0,0,NaN,0,10,Partially cloudy,partly-cloudy-night
20,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T20:00:00,1.7,0.1,0.0,88.47,...,130,1020.0,48,14.6,0,NaN,0,10,Partially cloudy,partly-cloudy-night
21,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T21:00:00,1.7,0.1,0.0,88.47,...,140,1020.0,54,16.4,0,NaN,0,10,Partially cloudy,partly-cloudy-night
22,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T22:00:00,1.7,0.1,0.0,88.47,...,150,1020.0,59,17.3,0,NaN,0,10,Partially cloudy,partly-cloudy-night
23,"28778, Swannanoa, NC, United States",Swannanoa NC 28778,"28778, Swannanoa, NC, United States",35.6,-82.403,2022-12-13T23:00:00,1.2,-0.4,0.0,91.70,...,140,1020.0,61,19.2,0,NaN,0,10,Partially cloudy,partly-cloudy-night

In [3]:
data.iloc[0,:]

name                28778, Swannanoa, NC, United States
address                              Swannanoa NC 28778
resolvedAddress     28778, Swannanoa, NC, United States
latitude                                           35.6
longitude                                       -82.403
datetime                            2022-12-13T00:00:00
temp                                                8.0
feelslike                                           6.2
dew                                                 4.9
humidity                                          80.79
precip                                                0
precipprob                                            0
preciptype                                          NaN
snow                                                  0
snowdepth                                             0
windgust                                           18.4
windspeed                                          10.1
winddir                                             143
sealevelpressure                                 1021.9
cloudcover                                          100
visibility                                         16.0
solarradiation                                        0
solarenergy                                         NaN
uvindex                                               0
severerisk                                           10
conditions                                     Overcast
icon                                             cloudy
Name: 0, dtype: object

In [9]:
def what_be_time(data=data):
  date= data.iloc[:,5] #looking at time columns
  for i in range(0,24): #now the rows(i)
    x= time.strptime(date[i],"%Y-%m-%dT%H:%M:%S")
    y = time.localtime()
    if y.tm_hour-5==x.tm_hour: #how to add time zones?
      return i
print(what_be_time())
def sunlight(data=data): #21
  data1 = data.iloc[:,21]
  for i in range(16,24):
    if data1[i] == 0:
      return i
sunlight()

10

18

In [10]:
def forcast(col, data=data):
  row = what_be_time(data)
  sunset = sunlight(data)
  #forcast = data.iloc[row:sunset,col] 
  forcast = data.iloc[row:24,col]
  forcast1 = []
  for row in forcast:
    forcast1.append(row)
  return forcast1

forcast(col=11)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 2, 2, 2]

In [6]:
def mean(row,data=data):
  forcast2 = forcast(row)
  n = 0
  sum = 0
  for row in forcast2:
    sum += row
    n += 1
  return( sum / n)
mean(6)

4.125

In [11]:
def min(row, data=data):
  forcast2 = forcast(row)
  min = forcast2[0]
  for row in forcast2:
    if row < min:
      min = row
  return min
def max(row, data=data):
  forcast2 = forcast(row)
  max = forcast2[0]
  for row in forcast2:
    if row > max:
      max = row
  return max
max(7)

3.9

In [12]:
def median(row,data=data):
  forcast2 = forcast(row)
  forcast2.sort()
  sum = 0
  for row in forcast2:
    sum += 1
  if sum % 2 == 1: #odd 
    i = (sum/2) - .5
    i = int(i)
    x = forcast2[i]
  elif sum % 2 == 0: #evin
    i1 = sum/2
    i2 = i1 + 1
    i1 = int(i1-1)
    i2 = int(i2-1)
    x = (forcast2[i1] + forcast2[i2])/2
  return x

median(6)

3.4

In [13]:
def squ(row, data=data):
  mean1 = mean(row)
  median1 = median(row)
  if mean1 == median1:
    string = mean1 #"normal"
  elif mean1 < median1:
    string = median1 #"left"
  elif mean1 > median1:
    string = mean1 #"right"
  return string
squ(6)

3.4

In [14]:
def tempscil(data=data): #col 6 and 7
  tep = squ(7)
  x = True
  if tep >=35: #'Shirt_sleeveless' #'Exercise_shorts'
    leval = .20
    y = 0 #"or lower"
  elif tep < 35: #'Tshirt' #'Shorts'
    leval = .25
    y = 0 #or lower"
    if tep < 30 and tep >= 25: #'Shirt_long_sleeves' #'Shorts'
      leval = .30
    elif tep < 25 and tep >= 20: #'Light_dress_sleeveless
      leval = .35
    elif tep < 20 and tep >= 15: #'Dress_long_sleeves'
      leval = .40
    elif tep < 15 and tep >= 20: #'Flannel_shirt_long_sleeves' #'Tshirt'  #'Shorts'
      leval = .45
    elif tep < 10: #'Flannel_shirt_long_sleeves' #'Shirt_long_sleeves'  #'Shorts'
      leval = .55
      y = 1 #"or wormer"
      if tep < 7 and tep >= 4: #'Thin_sweater' #'Tshirt' #'Jeans'
        leval = .70
      elif tep < 4 and tep >= 0: #'Thick_sweater' #'Shirt_long_sleeves' #'Jeans'
        leval = .85
      elif tep < 0 and tep >= -2: #'Thick_sweater' #'Shirt_long_sleeves' #'Jeans' #'Base_layer'
          leval = 1.00
      elif tep <-2 and tep >= -5: #'Thick_sweater' #'Shirt_long_sleeves' #'Jeans' #'Base_layer' #'Base_layer'
          leval = 1.20
      elif tep <-5 and tep >= -8: #'Thick_sweater' #'Shirt_long_sleeves' #'Corduroy' #'Base_layer' #'Base_layer'
          leval = 1.40
      elif tep < -8 and tep >= -11: #'Thick_sweater' #'Shirt_long_sleeves' #'Corduroy' #'Base_layer' #'Base_layer'
          leval = 1.60
      elif tep < -11 and tep >= -15: #'Thick_sweater' #'Shirt_long_sleeves' #'Corduroy' #'Base_layer' #'Base_layer'
          leval = 1.80
      elif tep < -15: #'Thick_sweater' #'Shirt_long_sleeves' #'Corduroy' #'Base_layer' #'Base_layer'
          leval = 2
  print(leval)
  return leval, y

In [15]:
def rainscail(data=data):#11
  x = max(11)
  print(x)
  y = 0
  tipe = 1
  if x >= 40:
    if max(13) == 0: #snow
      y = max(10) #rain
      tipe = 1 #rain
    else:
      y = max(13)
      tipe = 0 #snow
  else:
    return y ,tipe
  return y , tipe
    
rainscail()

2

(0, 1)

In [18]:
closet = {"Shirts" : 
          {'Tshirt':0.09 ,'Shirt_sleeveless':0.06,'Shirt_long_sleeves':0.14,"Running":0.06,"Light_Short_Sleeve_Shirt":0.10,"Overshirt":0.12,"Swim_top":0.05},
          "Shirts_layers":
          {'Base_layer':0.20,'Flannel_shirt_long_sleeves':0.30,'Thin_sweater':0.26,'Thick_sweater':0.35},
          "Underwer":
          {'Underwer':0.05},
          "Pants":
          {'Exercise_shorts':0.06,'Shorts':0.11,'Formal':0.20,'Jeans':0.25,'Corduroy':0.28,'Overalls':0.28,"Sweatpants":0.35,"Swim_bottoms":0.06, "Skirt":0.09},
          "Pants_layers":
          {'Base_layer':0.20,"Snow_Pants":0.55},
          "Whole":
          {'Coveralls':0.49,'Insulating_coveralls':1.13,'Light_dress_sleeveless':0.25,'Dress_long_sleeves':0.40},
          "Outerwear_tops":
          {'Raincoat':0.25,'Sweatshirt':0.35,'Down_jacket':0.55,'Coat':0.60,"Cape":.20},
          "Shoes":
          {'Shoes':0.02,'Boots':0.05},
          'Socks':
          {'Socks':0.02,'Thick_socks':0.10,'long_socks':0.06}}

In [21]:
def outfit(data=data,closet=closet):
  outfit1 = {"Pants":{},"Pants_layers":{},"Shirts":{},"Shirts_layers":{},"Whole":{},"Outerwear_tops":{},"Shoes":{},'Socks':{},"Underwer":{}}
  outfit1["Underwer"].update({"Underwer":closet["Underwer"]["Underwer"]})
  tep = tempscil()[0]
  #tep = .20
  if rainscail()[0] != 0:
    outfit1["Shoes"].update({"Boots":closet["Shoes"]["Boots"]})
    if rainscail()[1] == 1:
      outfit1["Outerwear_tops"].update({"Light_summer_jacket":closet["Outerwear_tops"]["Light_summer_jacket"]})
    elif rainscail()[1] ==0:
      if tep <= 1:
        outfit1["Outerwear_tops"].update({"Light_summer_jacket":closet["Outerwear_tops"]["Light_summer_jacket"]})
      elif tep > 1 and tep < 1.80:
        outfit1["Outerwear_tops"].update({"Down_jacket":closet["Outerwear_tops"]["Down_jacket"]})
      elif tep >= 1.80:
        outfit1["Outerwear_tops"].update({"Coat":closet["Outerwear_tops"]["Coat"]})
  else:
    outfit1["Shoes"].update({"Shoes":closet["Shoes"]["Shoes"]})
    if tep >= 1 and tep < 1.20:
      outfit1["Outerwear_tops"].update({'Light_summer_jacket':closet["Outerwear_tops"]['Light_summer_jacket']})
    elif tep >= 1.20 and tep < 1.60:
      outfit1["Outerwear_tops"].update({'Sweatshirt':closet["Outerwear_tops"]['Sweatshirt']})
    elif tep >= 1.60 and tep < 2:
      outfit1["Outerwear_tops"].update({'Down_jacket':closet["Outerwear_tops"]['Down_jacket']})
    elif tep == 2:
      outfit1["Outerwear_tops"].update({'Coat':closet["Outerwear_tops"]['Coat']})
  if tep >= 1.20:
    outfit1['Socks'].update({"Thick_socks":closet['Socks']["Thick_socks"]})
  elif tep <= .25:
    pass
  else:
    outfit1['Socks'].update({"Socks":closet['Socks']["Socks"]})
  if tep == .20:
    outfit1["Shirts"].update({"Shirt_sleeveless":closet["Shirts"]["Shirt_sleeveless"]})
  elif tep == .25:
    outfit1["Shirts"].update({'Tshirt':closet["Shirts"]['Tshirt']})
  elif tep == .30:
    outfit1["Shirts"].update({'Shirt_long_sleeves':closet["Shirts"]['Shirt_long_sleeves']})
  elif tep == .35:
    outfit1["Whole"].update({'Light_dress_sleeveless':closet["Whole"]['Light_dress_sleeveless']})
  elif tep == .40:
    outfit1["Whole"].update({'Dress_long_sleeves':closet["Whole"]['Dress_long_sleeves']})
  elif tep == .45 or tep ==.55:
    outfit1["Shirts"].update({'Flannel_shirt_long_sleeves':closet["Shirts"]['Flannel_shirt_long_sleeves']})
    if tep == .45:
      outfit1["Shirts"].update({'Tshirt':closet["Shirts"]['Tshirt']})
    else:
      outfit1["Shirts"].update({'Shirt_long_sleeves':closet["Shirts"]['Shirt_long_sleeves']})
  elif tep == .70:
    outfit1["Shirts_layers"].update({'Thin_sweater':closet["Shirts_layers"]['Thin_sweater']})
    outfit1["Shirts"].update({'Tshirt':closet["Shirts"]['Tshirt']})
  elif tep >= .85:
    outfit1["Shirts_layers"].update({'Thick_sweater':closet["Shirts_layers"]['Thick_sweater']})
    outfit1["Shirts"].update({'Shirt_long_sleeves':closet["Shirts"]['Shirt_long_sleeves']})
    if tep >= 1.20:
      outfit1["Shirts_layers"].update({'Base_layer':closet["Shirts_layers"]['Base_layer']})
  if tep == .20:
    outfit1['Pants'].update({'Exercise_shorts':closet["Pants_layers"]['Exercise_shorts']})
  elif tep >= .25 and tep < .70:
    outfit1["Pants"].update({'Shorts':closet["Pants"]['Shorts']})
  elif tep >= .70 and tep < 1:
    outfit1["Pants"].update({'Jeans':closet["Pants"]['Jeans']}) 
  elif tep >= 1:
    outfit1["Pants_layers"].update({'Base_layer':closet["Pants"]['Base_layer']})
    if tep >= .70 and tep < 1.40:
      outfit1["Pants"].update({'Jeans':closet["Pants"]['Jeans']})
    if tep >= 1.40:
      outfit1["Pants"].update({'Corduroy':closet["Pants"]['Corduroy']})
  sum1 = sum(outfit1["Shirts"].values()) + sum(outfit1['Pants'].values()) + sum(outfit1['Whole'].values()) + sum(outfit1['Outerwear_tops'].values()) + sum(outfit1['Shoes'].values())+sum(outfit1['Socks'].values())+sum(outfit1['Underwer'].values())+sum(outfit1["Shirts_layers"].values()) + sum(outfit1["Pants_layers"].values())
  return sum1, outfit1
outfit()

0.85
2

(0.8300000000000001,
 {'Pants': {'Jeans': 0.25},
  'Pants_layers': {},
  'Shirts': {'Shirt_long_sleeves': 0.14},
  'Shirts_layers': {'Thick_sweater': 0.35},
  'Whole': {},
  'Outerwear_tops': {},
  'Shoes': {'Shoes': 0.02},
  'Socks': {'Socks': 0.02},
  'Underwer': {'Underwer': 0.05}})

# New Section

In [62]:
def outfit_new(data=data,closet=closet):
  list =[]
  for x in closet.keys():
    for y in closet[x].keys():
      list.append(y)
  outfit1 = {"Pants":{},"Pants_layers":{},"Shirts":{},"Shirts_layers":{},"Whole":{},"Outerwear_tops":{},"Shoes":{},'Socks':{},"Underwer":{'Underwer':0.05}}
  t = random.randrange(6,10)
  for x in range(t):
    u = list[random.randint(0, len(list)-1)]
    try:
      outfit1["Pants"].update({u:closet["Pants"][u]})
    except KeyError:
      try:
        outfit1["Shirts"].update({u:closet["Shirts"][u]})
      except KeyError:
        try:
          outfit1["Shoes"].update({u:closet["Shoes"][u]})
        except KeyError:
          try:
            outfit1["Outerwear_tops"].update({u:closet["Outerwear_tops"][u]})
          except KeyError:
            try:
              outfit1["Whole"].update({u:closet["Whole"][u]})
            except KeyError:
              try:
                outfit1['Socks'].update({u:closet['Socks'][u]})
              except KeyError:
                try:
                  outfit1["Pants_layers"].update({u:closet["Pants_layers"][u]})
                except KeyError:
                  try:
                    outfit1["Shirts_layers"].update({u:closet["Shirts_layers"][u]})
                  except KeyError:
                    outfit1["Underwer"].update({u:closet["Underwer"][u]})
  sum1 = sum(outfit1["Shirts"].values()) + sum(outfit1['Pants'].values()) + sum(outfit1['Whole'].values()) + sum(outfit1['Outerwear_tops'].values()) + sum(outfit1['Shoes'].values())+sum(outfit1['Socks'].values())+sum(outfit1['Underwer'].values())+sum(outfit1["Shirts_layers"].values()) + sum(outfit1["Pants_layers"].values())
  return sum1, outfit1
outfit_new()

(1.33,
 {'Pants': {'Exercise_shorts': 0.06, 'Jeans': 0.25},
  'Pants_layers': {},
  'Shirts': {'Shirt_long_sleeves': 0.14, 'Shirt_sleeveless': 0.06},
  'Shirts_layers': {'Thin_sweater': 0.26},
  'Whole': {'Coveralls': 0.49},
  'Outerwear_tops': {},
  'Shoes': {},
  'Socks': {'Socks': 0.02},
  'Underwer': {'Underwer': 0.05}})

In [ ]:
def check_1():
  outfit1 = outfit_new()
  x = False
  while x == False:
    if tempscil()[1] == 0:
      print(f"runing...{outfit1[0]}")
      if outfit1[0] <= tempscil()[0]:
        if check_2(outfit1[1]):
          print(outfit1[1])
          break
        else:
          check_1()
      else:
        check_1()
    else:
      print(f"runing...{outfit1[0]}")
      if outfit1[0] >= tempscil()[0]:
        if check_2(outfit1[1]):
          print(outfit1[1])
          break
        else:
          check_1()
      else:
        check_1()
check_1()

In [ ]:
def check_1_new():
  outfit1 = outfit_new()
  x = False
  while x == False:
    if tempscil()[1] == 0:
      print(f"runing...{outfit1[0]}")
      if outfit1[0] <= tempscil()[0]:
          print(outfit1[1])
          break
      else:
        check_1_new()
    else:
      print(f"runing...{outfit1[0]}")
      if outfit1[0] >= tempscil()[0]:
        print(outfit1[1])
        break
      else:
        check_1_new()
check_1()

In [61]:

def check_2(outfit):
  if sum(outfit['Whole'].values()) > 0:
    if sum(outfit['Shoes'].values()) > 0:
      if sum(outfit['Underwer'].values()) > 0:
        return True
  elif sum(outfit['Shirts'].values()) > 0:
    if sum(outfit['Pants'].values()) > 0:
      if sum(outfit['Shoes'].values()) > 0:
        if sum(outfit['Underwer'].values()) > 0:
          return True

In [ ]:
def check_random():
  outfit1 = outfit_new()
  x = False
  while x == False:
    if tempscil()[1] == 0:
      print(f"runing...{outfit1[0]}")
      if check_2(outfit1[1]):
        print(outfit1[1])
        break
      else:
        check_random()
    else:
      print(f"runing...{outfit1[0]}")
      if check_2(outfit1[1]):
        print(outfit1[1])
        break
      else:
        check_random()
  print("Dune")
check_1()

# New Section

In [ ]:
hi = outfit()
hi[0]
hi[1]
hi[1].keys()

In [ ]:
closet = {  "Shirts" : 
          {'Tshirt':0.09 ,'Shirt_sleeveless':0.06,'Shirt_long_sleeves':0.12,'Base_layer':0.14,'Normal_shirt_long_sleeves':0.25,'Flannel_shirt_long_sleeves':0.30,'Long_sleeves_turtleneck_blouse':0.34,'Sleeveless_vest':0.12,'Thin_sweater':0.20,'Long_thin_sleeves_sweater':0.26,'Thick_sweater':0.35,'Long_thick_sleeves_turtleneck':0.37},
          'Underwer':0.05,
          "Pants":
          {'Exercise_shorts':0.06,'Shorts':0.11,'Light_trousers':0.20,'Normal_trousers':0.25,'Flannel_trousers':0.28,'Overalls':0.28,},"Whole":
          {'Coveralls':0.49,'Insulating_coveralls':1.13,'Light_dress_sleeveless':0.25,'Dress_long_sleeves':0.40},
          "Outerwear_tops":
          {'Vest':0.13,'Light_summer_jacket':0.25,'Sweatshirt':0.35,'Down_jacket':0.55,'Coat':0.60,'Parka':0.70},
          "Shoes":
          {'Shoes':0.02,'Boots':0.05},
          'Socks':
          {'Socks':0.02,'Thick_socks':0.10}}

In [ ]:
def standered_devation(row,data=data): #this fution is uslis to me now :(
  forcast2 = forcast(row)
  mean1 = mean(row)
  n = 0
  sum = 0
  for row in forcast2:
    sum += row
    n += 1
  sd_sum=0
  for row in forcast2:
    x = (row-mean1)**2
    sd_sum += x
  y = sd_sum / (n-1)
  sd = y**(1/2)
  return int(sd+.5)
standered_devation(6)


  if tep >= 20: #room temperature worm
    y ="or lower"
    if tep >=30: #86f
      if tep >=35: #95f Hot!!
        leval= .20
      else: #30-34c
        leval= .25 
    elif tep >= 25: #25-29c
      leval= .30
    else: #20-24f
      leval = .35
  elif tep < 20:  
    y ="or higher"
    if tep < 15:
      leval = .40
      if tep < 10:
        leval =.50
        if tep < 5:
          leval = .60
          if tep < 0:
            leval = .70
            if tep <-5:
              leval =.80
              if tep <-10:
                leval= .90
                if tep<-15:
                  leval=1

In [ ]:
#time.strptime("2022-11-14 01:00:00","%Y-%m-%d %H:%M:%S")
time.strptime(date[1],"%Y-%m-%dT%H:%M:%S")

In [ ]:
End_disonery ={"pants":{}}
End_disonery['pants'].update({'Tshirt':closet['Shirts']['Tshirt']})
print(End_disonery)

In [ ]:
x = time.localtime()
x

{'Pants': {'Base_layer': 0.2}, 'Pants_layers': {}, 'Shirts': {'Flannel_shirt_long_sleeves': 0.3, 'Tshirt': 0.09, 'Shirt_long_sleeves': 0.12}, 'Shirts_layers': {}, 'Whole': {'Insulating_coveralls': 1.13}, 'Outerwear_tops': {'Sweatshirt': 0.35, 'Down_jacket': 0.55}, 'Shoes': {'Boots': 0.05}, 'Socks': {}, 'Underwer': {}}